Controllers/TimeTableController.cs
using GeneticAlgorithms.Entity.DTOs;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GeneticAlgorithms.Controllers;

public class TimeTableController : Controller
{
    private readonly DataContext _ctx;
    
    public TimeTableController(DataContext ctx)
    {
        _ctx = ctx;
    }
    
    [HttpGet]
    public async Task<ActionResult> Index()
    {
            var schudels = await _ctx.TimeSlots
                .Include(i => i.Course)
                .ThenInclude(t => t.Teacher)
                .Include(c => c.Course)
                .ThenInclude(s => s.StudentCourses)
                .Include(p => p.Place)
                .Select(s => new TimeSlotDto
                {
                    Course = s.Course.Title,
                    Place = s.Place.Title,
                    Start = s.Start.TotalMilliseconds,
                    End = s.End.TotalMilliseconds,
                    Students = s.Course.StudentCourses.Count,
                    Day = (int)s.Day
                })
                .ToListAsync();

            return View(schudels);
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - GeneticAlgorithms</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/GeneticAlgorithms.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="TimeTable" asp-action="Index">GeneticAlgorithms</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="TimeTable" asp-action="Index">Home</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - GeneticAlgorithms 
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/TimeTable/Index.cshtml
@model IEnumerable<GeneticAlgorithms.Entity.DTOs.TimeSlotDto>

@{
    ViewData["Title"] = "Index";
}

<h1>Розклад</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                День
            </th>
            <th>
                Початок
            </th>
            <th>
                Кінець
            </th>
            <th>
                Аудиторія
            </th>
            <th>
                Курс
            </th>
            <th>
                Студенти
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Day)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Start)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.End)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Place)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Course)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Students)
            </td>
        </tr>
}
    </tbody>
</table>